bpy_speckle/convert/from_speckle/brep.py
bpy_speckle/convert/from_speckle/curve.py
bpy_speckle/convert/from_speckle/mesh.py

`Line` does not have attribute `Value`.
we need to check for the start and end points instead.
start will always exist. it's possible that end will be `None`
dim's beautiful model can now be received!
also makes a fix in mesh conversion looking for name and does some light refactoring to reduce nesting

fix(convert): fix Line conversions

---

bpy_speckle/__init__.py
bpy_speckle/functions.py
bpy_speckle/install_dependencies.py

oopsies so sorry about this 🙃
I guess I didn't fully clean my modules and so i missed these import errors the first go around

feat(specklepy): fix import errors!!

---

bpy_speckle/convert/__init__.py
bpy_speckle/convert/util.py
bpy_speckle/operators/streams.py
poetry.lock
pyproject.toml

this can be refactored quite a bit to make it cleaner, but am merging for now to give people a go at trying out the new functionality 
- human readable object names when receiving from speckle
- support for simple materials to / from speckle
- preserves collection hierarchy on send and receive 
closes #17 & #4

Materials and collections hierarchy 

---

bpy_speckle/operators/streams.py

lmao i'm dumb - one line fix here
ty @AlanRynne for spotting this 💕

fix(streams): *correctly* detach collections

---

bpy_speckle/convert/from_speckle/brep.py

fix(convert): check display val & mesh for breps

---

bpy_speckle/convert/__init__.py
bpy_speckle/convert/from_speckle/brep.py
bpy_speckle/convert/from_speckle/mesh.py
poetry.lock

- try except for `faces.new()` to proceed with commit receive
- temp disable applying transforms on receive 
- checking for display val and mesh

fix(receive): some prelim geometry fixes

---

bpy_speckle/convert/__init__.py
bpy_speckle/convert/to_speckle/curve.py
bpy_speckle/convert/to_speckle/mesh.py
bpy_speckle/functions.py
bpy_speckle/operators/object.py

- object level unit handling (closes #33)
- bubbles up `applicationId` on send if objects originated from a diff application
- removes wrong assignments of `applicationId`
- bit of cleanup around curve convesions

General fixes regarding units, curves, and props

---

bpy_speckle/operators/streams.py

finally figured out what was happening w this bug 🥳

fix(receive): handle nested lists from grasshopper

---

bpy_speckle/operators/streams.py

tested with offending streams as well as latest test streams from Rhino & Revit - all is well!
closes #44

fix(receive): resolve bug when receiveing 🦗 CSO

---

bpy_speckle/operators/__init__.py
bpy_speckle/operators/misc.py
bpy_speckle/ui/__init__.py
bpy_speckle/ui/view3d.py

feat(ui): help panel w links to docs, tuts, forum

---

bpy_speckle/operators/__init__.py
bpy_speckle/operators/streams.py
bpy_speckle/operators/users.py
bpy_speckle/ui/view3d.py
poetry.lock
pyproject.toml

adds a little button in the stream panel to paste in a stream url
((accepts more complex url, but only selects by stream id, branch, and commit. objects can't be selected))
closes #42

feat(ui): add stream, branch, or commit by url

---

bpy_speckle/convert/__init__.py
bpy_speckle/operators/streams.py

seems to work from my tests, but will want to see how actual users find it!
closes #36

feat(send): toggle applying modifiers

---

bpy_speckle/operators/streams.py
poetry.lock
pyproject.toml

feat(streams): add read reciepts + update to specklepy 2.4

---

.circleci/config.yml

adds specklepy install to the build step as it needs to happen in a windows env! this is a bit messy, but i think the easiest solution for now /shrug

ci: fix install platform

---

bpy_speckle/convert/__init__.py

makes it easier to work w geo from places like revit

feat(convert): add parent type to display meshes

---

bpy_speckle/convert/__init__.py
poetry.lock
pyproject.toml

fix a minor issue with handling list display meshes and bump specklepy to get the nulls setting hotfix
closes #76

fix(convert): nulls on receive

---

bpy_speckle/convert/to_native.py
bpy_speckle/operators/streams.py
bpy_speckle/operators/users.py
poetry.lock
pyproject.toml

we on py 2.6.0 💃
also display vals wheeee
closes #79 and #80

fix(convert): new `displayValue` to native & specklepy update

---

bpy_speckle/convert/to_speckle.py

fix(converter): skip if not `Pincipled BSDF`

---

bpy_speckle/convert/__init__.py
bpy_speckle/convert/to_native.py
bpy_speckle/convert/to_speckle.py
bpy_speckle/convert/util.py
bpy_speckle/operators/streams.py
bpy_speckle/operators/users.py
poetry.lock
pyproject.toml

add custom props to each mesh
TODO: combine display values into multimaterial meshes and attach props to that instead

feat(convert): temps custom props patch

---

.circleci/config.yml

- initial adaptation of the `build-connector-mac` job in sharp tailored for the blender connector (eg doesn't need objects or building)

ci: initial mac install ci

---

.circleci/config.yml
bpy_speckle/clients.py
bpy_speckle/convert/__init__.py
bpy_speckle/convert/to_native.py
bpy_speckle/convert/to_speckle.py
bpy_speckle/convert/util.py
bpy_speckle/functions.py
bpy_speckle/operators/streams.py
bpy_speckle/operators/users.py

Added receive option to "Clean" incoming geometry.
Performs a **Limited Dissolve**, with 0.1° angle, and a **Merge Vertices by distance** (remove_doubles) with a threshold of 0.001
on received geometry.
closes #109

Clean Mesh

---

.circleci/config.yml

Description of PR...
- Item 1
- Item 2
(optional)
Include **important** links regarding the implementation of this PR.
This usually includes and RFC or an aggregation of issues and/or individual conversations
that helped put this solution together. This helps ensure there is a good aggregation
of resources regarding the implementation.
```text
Fixes #85, Fixes #22, Fixes username/repo#123
Connects #123
```

clone ci tools with ssh, use circleci context for env vars

---

bpy_speckle/convert/util.py

Custom Properties overflow fix

---

bpy_speckle/installer.py

This makes sure the blender vscode debugger can work.

unbreak the debugger

---

bpy_speckle/operators/users.py
bpy_speckle/properties/scene.py

Authtoken will no longer be saved to blender file

fix(auth): hotfix for serializing authTokens in blender file

---

bpy_speckle/__init__.py
bpy_speckle/convert/to_native.py
bpy_speckle/convert/to_speckle.py
bpy_speckle/convert/util.py
bpy_speckle/installer.py
bpy_speckle/properties/scene.py

Ignore branch name
Added new installer see https://github.com/specklesystems/specklepy/pull/266

Using new installer.py

---

bpy_speckle/operators/streams.py
bpy_speckle/operators/users.py
bpy_speckle/properties/scene.py

see https://github.com/specklesystems/admin/issues/389

Added `isMultiplayer` property

---

bpy_speckle/blender_commit_object_builder.py
bpy_speckle/convert/to_native.py
bpy_speckle/convert/to_speckle.py
bpy_speckle/functions.py
bpy_speckle/operators/commit.py
bpy_speckle/operators/streams.py
bpy_speckle/operators/users.py
bpy_speckle/properties/scene.py
bpy_speckle/specklepy_extras/commit_object_builder.py
bpy_speckle/specklepy_extras/traversal.py
poetry.lock
pyproject.toml

Implemented support for receiving and sending using the new Collections class.
Also implemented traversal refactor

Collections

---

bpy_speckle/convert/to_native.py

feat(converter): support for view/cameras

---

bpy_speckle/blender_commit_object_builder.py
bpy_speckle/convert/to_native.py
bpy_speckle/convert/to_speckle.py
bpy_speckle/convert/util.py
bpy_speckle/operators/commit.py
bpy_speckle/operators/misc.py
bpy_speckle/operators/object.py
bpy_speckle/operators/streams.py
bpy_speckle/operators/users.py
bpy_speckle/properties/scene.py
bpy_speckle/ui/object.py
poetry.lock
pyproject.toml

TODO Before merge & release : `poetry lock`

2.18 Update

---

bpy_speckle/converter/to_native.py

adds the scaling functionality (that we had in v2)

fix: add the scaling function

---

bpy_speckle/connector/ui/main_panel.py

group model cards by project

---

bpy_speckle/converter/to_native.py

Materials weren't being correctly applied to the objects when model only contains DataObjects. This was due to a hierarchy mismatch where the `applicationId` exists on parent objects but not on their display meshes.
Now proper hierarchical material inheritance is implemented while preserving direct material assignments where they exist.

fix: applying materials to objects properly

---

bpy_speckle/converter/to_native.py

adds native conversions for:
- arc
- circle
- ellipse

feat: native speckle to blender conversion

---

bpy_speckle/converter/to_native.py
pyproject.toml
uv.lock

adds conversions for curve, polycurve and point

feat: converter functions for curve, polycurve and point

---

bpy_speckle/connector/operations/load_operation.py
bpy_speckle/converter/to_native.py
bpy_speckle/converter/utils.py

Adds the functionality of converting instance proxies.

feat: conversion of instance proxies

---

bpy_speckle/connector/utils/version_manager.py

adds a none check for the version messages

fix: none check for version messages

---

bpy_speckle/converter/to_native.py

adds a material mapping to avoid existing material overriding

feat: material consistency

---

bpy_speckle/connector/blender_operators/add_project_by_url.py
bpy_speckle/connector/ui/main_panel.py
bpy_speckle/connector/ui/project_selection_dialog.py
bpy_speckle/connector/utils/account_manager.py
bpy_speckle/connector/utils/project_manager.py

- disables the functionality of latest button (which was crashing) in the model card which is just an info tab
- lists all the available projects in a workspace, greys out the ones that user does not have permission to load (aligns with DUI3 behaviour)
- blocks loading project by url if user does not have the permission

fix: checks for permissions

---

bpy_speckle/converter/to_native.py

- #### Degree 2 NURBS/ellipse/arc curves:
Blender can’t represent degree 2 (quadratic) NURBS curves (like ellipses and arcs) perfectly. Now, if we detect a degree 2 curve, we fallback to using the displayValue 
- #### Arcs:
Using the right number of points to make smooth curves. Making sure arcs curve in the right direction.
- #### Polycurves:
Polycurves are now imported by converting each segment (line, arc, etc.) as its own separate spline in Blender.

fix: better arc and curve conversion

---

bpy_speckle/converter/to_native.py

applies arc properties to polycurve segments

fix: adds properties to polycurves

---

README.md

updates the readme for v3-dev branch

update readme for v3-dev

---

pyproject.toml
uv.lock

updates the specklepy version to keep up with the latest queries

fix: updates the sdk version

---

bpy_speckle/__init__.py
bpy_speckle/connector/blender_operators/publish_button.py
bpy_speckle/connector/states/speckle_state.py
bpy_speckle/connector/ui/main_panel.py
bpy_speckle/connector/ui/selection_filter_dialog.py

let's work only on bilal/send-ui branch.

Bilal/cnx 1880 implement send UI
