specklesystems/speckle-blender

- bpy_speckle/operators/users.py
not all user fields are mandatory, and this would break the client creation logic as it was not handled. this change adds defaults so accounts will be successfully added.
closes #7
> fix(users): handle accts w/out company/server name

- bpy_speckle/operators/users.py
this was not getting set previously meaning operations did not work for
accounts on servers other than speckle.xyz
(( should have added this in the prev PR soz, but i just noticed it after merging 🙈 ))
> fix(users): set server url correctly

- .gitignore
- bpy_speckle/__init__.py
- bpy_speckle/convert/__init__.py
- bpy_speckle/convert/from_speckle/curve.py
- bpy_speckle/convert/to_speckle/curve.py
- bpy_speckle/convert/to_speckle/mesh.py
- bpy_speckle/functions.py
- bpy_speckle/install_dependencies.py
- bpy_speckle/operators/object.py
- bpy_speckle/operators/streams.py
- bpy_speckle/operators/users.py
- bpy_speckle/properties/scene.py
- poetry.lock
- pyproject.toml
[specklepy is now on pypi!!](https://pypi.org/project/specklepy/)
in order to avoid conflicts with the 1.0 package, the 2.0 package has been called `specklepy`. i've updated all refs here to reflect this and all seems well to me.
> Update Speckle Ref

- README.md
- bpy_speckle/operators/streams.py
- bpy_speckle/operators/users.py
- bpy_speckle/ui/view3d.py
- poetry.lock
- pyproject.toml
- updates to `specklepy 2.2.2`
- manage case for unsupported / invalid speckle accounts
- null check for objects outside of collections (closes #26)
- due to collections thing, renames the `data` field to `objects` so the viewer can parse all blender objects
- updates text on ui button for opening stream in browser
> Bug fixes: incompatible accounts and objects outside of collections

- bpy_speckle/convert/__init__.py
- bpy_speckle/convert/from_speckle/curve.py
- bpy_speckle/operators/streams.py
- bpy_speckle/operators/users.py
- fixes for arc and nurb conversions (rhino std geometry test file now comes through successfully!)
- log (just in console for now) and skip unsupported elements
- always try and fall back on display mesh / value but preserve actual speckle type as name (everything in revit test file except for room boundaries, model curves, openings, and direct shapes now at least show up as meshes with the correct name even if not truly converted)
- add "blender" as the source for commits
- increase stream fetch limit to 20
> feat(conversions): improvements for `from_speckle` conversions

- .gitignore
- bpy_speckle/convert/from_speckle/mesh.py
- bpy_speckle/convert/to_speckle/mesh.py
Closes #56 
Modified ToSpeckle and ToNative mesh conversion to allow for n-gon faces.
Requires some further testing before is ready to merge.
ToSpeckle triangles and quads still use the 0 and 1 cardinality (rather than 3 and 4) at least for now until all our other connectors are updated to accept 3 and 4.
https://github.com/specklesystems/speckle-blender/blob/14aaf4f064cdb0e1c1a52d19132b4d54ccb5f295/bpy_speckle/convert/to_speckle/mesh.py#L34-L42
> Ngon Support

- poetry.lock
- pyproject.toml
attempting to resolve Plugin activation error due to `typing_extensions` #67
> chore: bump to specklepy 2.4.2

- .circleci/config.yml
- bpy_speckle/__init__.py
- poetry.lock
- pyproject.toml
- align with new sharp tagging system for installers
- upgrade to specklepy 2.6.6
- add blender version to metrics
> fix(installer/metrics): updates and cleanup

- bpy_speckle/convert/to_native.py
- bpy_speckle/convert/to_speckle.py
- bpy_speckle/operators/object.py
- bpy_speckle/operators/streams.py
- bpy_speckle/ui/view3d.py
- pyproject.toml
- removes some superficial depreciated units stuff
- passes down brep `renderMaterial` to each item in its `displayValue`
> fix(converter): pass brep materials to displayvals

- .circleci/config.yml
Activates CI runs for mac both in `build` and `deploy` workflows.
Changed the tag so that they'd all be released at the same time.
> ci: Activated both mac runs on build

- bpy_speckle/convert/__init__.py
- bpy_speckle/convert/to_native.py
- bpy_speckle/convert/to_speckle.py
- bpy_speckle/operators/streams.py
closes #126
Issue was due to me using type hinting syntax that that's unsupported in python 3.9 (what Blender 2.93 uses)
> Fixed issue with connector failing to load on Blender 2.93

- bpy_speckle/convert/to_native.py
- bpy_speckle/operators/streams.py
Fixed issue with receiving commits that contain empty lists, and dynamically detached "@displayValue" "@elements" props.
> fixed IFC commits with empty lists

- bpy_speckle/convert/to_native.py
- bpy_speckle/convert/to_speckle.py
- bpy_speckle/convert/util.py
- Several improvements to NURBS conversion ToNative and ToSpeckle
- Receiving NURBS from rhino should be perfect!
- Sending Non-Bézier NURBS should also work perfectly!
- Still some issues with sending Bézier nurbs. (see #153)
- Added displayValue for nurbs curves so that they can now display in the viewer.
- Still need to add the same for Bézier curves (see #152)
- Added Ellipse & Circle to native (Bézier) conversion
Before:
After:
Truth:
see #131
> Fixes many bugs with curves

- bpy_speckle/convert/to_native.py
- bpy_speckle/convert/util.py
- bpy_speckle/operators/streams.py
I noticed that QGIS sends vertex colours as uint32 (rather than signed int32)
Also, received meshes that don't have a render material, but do have vertex colours, will now have a default "color by color attribute" material.
> Fixed issue with uint32 vertex colours not parsing

- bpy_speckle/operators/streams.py
- bpy_speckle/ui/view3d.py
We offer a feature of the Blender UI to delete streams
And we do require the user to confirm that selection
But this feature is quite dangerous, and I'm concerned its too easy to delete the wrong project or users misunderstand that this deletes the entire project permanently
> deprecated delete stream

- bpy_speckle/convert/to_native.py
Updated nameing function for Revit families to include family type
> CNX-9351 add type name to collection name in blender for families from revit

- bpy_speckle/operators/users.py
- bpy_speckle/properties/scene.py
When user refreshes the stream, branch selection resets. As a workaround, I stored selected branch in a class member. Then used that value to get active branch. Better solutions are possible of course.
> Recover branch selection

- bpy_speckle/installer.py
This PR solves slowness on Blender startup.
Removes requirements file after initial installation.
Skips installing dependencies if requirements file is not found.
Always install dependencies when debugger is detected.
> Skip installing dependencies after initial install

- bpy_speckle/operators/streams.py
- bpy_speckle/operators/users.py
- bpy_speckle/properties/scene.py
- Set selected_commit_id to new commit id on send operation
- Fix resetting active_stream on restore_selection_state
- Avoid using integer variable (active_user) as conditional
> fix send stream object cases

- bpy_speckle/converter/to_native.py
- bpy_speckle/operators/load.py
- bpy_speckle/ui/model_card.py
- bpy_speckle/ui/version_selection_dialog.py
- bpy_speckle/utils/get_ascendants.py
- bpy_speckle/utils/model_manager.py
- bpy_speckle/utils/project_manager.py
- bpy_speckle/utils/version_manager.py
- pyproject.toml
- uv.lock
this pr adds the functionality of receiving from speckle using next-gen blender connector:
- generates a unique name for objects
- converts: line, polyline, mesh and displayvalue (as a fallback mechanism)
- creates a nested collection in blender mimicking the received speckle model hierarchy
> feat: first receive with next-gen blender connector

- bpy_speckle/converter/to_native.py
When converting models with instances in non-metric units the transformations were incorrect because the unit conversion was hard-coded. Related to the issue:
https://linear.app/speckle/issue/CNX-1774/loading-sketchup-models-in-blender
- Removed hardcoded unit conversions in `proxy_scale`
- Integrated with Speckle's unit system for consistent unit handling
- Added proper error handling for unit conversion failures
> fix: unit conversion for instances

- bpy_speckle/converter/utils.py
[DO NOT MERGE UNTIL TESTED WITH SPECKLEPY FIXES]
This PR sets the viewport display value of the materials in Blender. It sets the diffuse colors and opacity from render materials.
This ends up in a much nicer looking default viewport. Its a nice UX improvement.
https://github.com/user-attachments/assets/9b3f85c4-785c-4b99-b0ab-0f4e8fb5e74c
> Set Viewport Display color of materials

- bpy_speckle/installer.py
this pr rolls back the name of the application for the installer - removing legacy tag
> v2 - renames the installer
